export default {
  id: {
    "/blog": "blog",
    "/syarat-ketentuan": "syarat-ketentuan",
    "/tentang-kami": "tentang-kami",
    "/cara-pemesanan": "cara-pemesanan-badut-maskot",
    "/": "halaman-depan",
    "/badut-maskot": "badut-maskot",
    "/credits": "credits",
    "/pencarian": "pencarian",
  },
  en: {
    "/en/blog": "en/blog",
    "/en/syarat-ketentuan": "en/syarat-ketentuan",
    "/en/tentang-kami": "en/tentang-kami",
    "/en/cara-pemesanan": "en/cara-pemesanan-badut-maskot",
    "/en": "en/homepage",
    "/en/badut-maskot": "en/badut-maskot",
    "/en/credits": "en/credits",
    "/en/portfolio": "en/portfolio",
    "/en/how-to-order": "en/how-to-order",
    "/en/about-us": "en/about-us",
    "/en/terms-and-conditions": "en/terms-and-conditions",
    "/en/search": "en/search",
  },
};
